language: node_js
node_js:
  - "9"
dist: trusty
sudo: false  
cache:
  directories:
    - "node_modules"
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - npm start &
  - sleep 5